Changes Related to wETH deposit and withdrawals backfill substream
Airstack-xyz/Substreams pull request #31
Opened 2024-02-09 13:46 UTC by Hrishikesh-Thakkar

<img width="821" alt="Screenshot 2024-02-09 at 7 15 43 PM" src="https://github.com/Airstack-xyz/Substreams/assets/25359325/02ff18ad-2a5e-4e07-a7cc-cd1fc0095206">
<img width="876" alt="Screenshot 2024-02-09 at 7 16 11 PM" src="https://github.com/Airstack-xyz/Substreams/assets/25359325/ccb2543a-4e90-4424-9849-b1fc248d79d5">

2024-02-14 15:24 UTC, 0xsarvesh requested changes
Overall looks good, some minor feedbacks

2024-02-14 15:24 UTC, 0xsarvesh commented on transfer-tracker/src/lib.rs
> +        if token_address == "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2".to_string(){
You can move this to yaml file.

2024-02-14 15:24 UTC, 0xsarvesh commented on transfer-tracker/src/lib.rs
> +                    from: String::from("0x0000000000000000000000000000000000000000"),
Take out zero address as constant

2024-02-14 15:24 UTC, 0xsarvesh commented on transfer-tracker/src/lib.rs
> +        if token_address == "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2".to_string(){
This address is chain specific?

2024-02-14 17:04 UTC, Hrishikesh-Thakkar commented on transfer-tracker/src/lib.rs
> +        if token_address == "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2".to_string(){
Yes only for ethereum

2024-02-15 15:31 UTC, 0xsarvesh approved these changes

2024-02-15 17:38 UTC, merged